

386_OBJECTS=\
 $(OBJ_PATH)\$O\miniport.obj \
 $(OBJ_PATH)\$O\passthru.obj \
 $(OBJ_PATH)\$O\protocol.obj \
 $(OBJ_PATH)\$O\analysispacket.obj \
 $(OBJ_PATH)\$O\hook.obj \


_RES_FILE=$(OBJ_PATH)\$O\passthru.res
PRECOMPILED_INCLUDE_BASENAME=precomp.h




# lowercased
BASEDIR=c:\winddk\7600.16385.1
OBJECT_ROOT=c:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=c:\passthru
OBJ_PATH=c:\passthru
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
